Repository TeamPetPoison/pet-poison-alert, pull requests merged in 2023-09, with the labels that each got.

#46 adding location api request
  packages/client/lib/components/LocationContext.jsx
  packages/client/lib/components/LocationSearch.jsx
  packages/client/lib/components/Map.jsx
  packages/client/lib/components/ReportForm/NavigationButtons/Submit.jsx
  packages/client/lib/components/useOnClickOutside.js
  packages/client/lib/components/useOnClickOutside.jsx
  packages/client/pages/_app.tsx
  packages/client/store/store.js
Labels: enhancement

#48 Make reusable `<SVGIcon />` and cleanup files/folders
  packages/client/lib/components/BottomNav/BottomNav.jsx
  packages/client/lib/components/BottomNav/BottomNavItem.jsx
  packages/client/lib/components/LocationContext.jsx
  packages/client/lib/components/LocationSearch.jsx
  packages/client/lib/components/Map.jsx
  packages/client/lib/components/ReportForm/FormViews/CategoryView.jsx
  packages/client/lib/components/ReportForm/FormViews/LocationView.jsx
  packages/client/lib/components/ReportForm/FormViews/PhotoView.jsx
  packages/client/lib/components/ReportForm/FormViews/SummaryView.jsx
  packages/client/lib/components/ReportForm/FormViews/TitleView.jsx
  packages/client/lib/components/ReportForm/FormViews/UpdateView.jsx
  packages/client/lib/components/ReportForm/NavigationButtons/Cancel.jsx
  packages/client/lib/components/ReportForm/NavigationButtons/Continue.jsx
  packages/client/lib/components/ReportForm/NavigationButtons/ExitForm.jsx
  packages/client/lib/components/ReportForm/NavigationButtons/FormButtons.jsx
  packages/client/lib/components/ReportForm/NavigationButtons/GoBack.jsx
  packages/client/lib/components/ReportForm/NavigationButtons/SubmitReportForm.jsx
  packages/client/lib/components/ReportForm/NavigationButtons/XMark.jsx
  packages/client/lib/components/ReportForm/ReportForm.jsx
  packages/client/lib/components/common/icons/Icon.jsx
  packages/client/lib/components/common/icons/SVGIcon.jsx
  packages/client/lib/firebase/firebaseConfig.js
  packages/client/lib/hooks/useOnClickOutside.jsx
  packages/client/pages/_app.tsx
  packages/client/pages/api/hello.ts
Labels: dev-experience

#49 Format prettier & tailwind classes
  .gitignore
  .prettierrc
  package-lock.json
  package.json
  packages/client/lib/components/BottomNav/BottomNav.jsx
  packages/client/lib/components/BottomNav/BottomNavItem.jsx
  packages/client/lib/components/LocationSearch.jsx
  packages/client/lib/components/Map.jsx
  packages/client/lib/components/ReportForm/FormViews/CategoryView.jsx
  packages/client/lib/components/ReportForm/FormViews/LocationView.jsx
  packages/client/lib/components/ReportForm/FormViews/PhotoView.jsx
  packages/client/lib/components/ReportForm/FormViews/SummaryView.jsx
  packages/client/lib/components/ReportForm/FormViews/TitleView.jsx
  packages/client/lib/components/ReportForm/FormViews/UpdateView.jsx
  packages/client/lib/components/ReportForm/NavigationButtons/ExitForm.jsx
  packages/client/lib/components/ReportForm/NavigationButtons/FormButtons.jsx
  packages/client/lib/components/ReportForm/NavigationButtons/SubmitReportForm.jsx
  packages/client/lib/components/ReportForm/ReportForm.jsx
  packages/client/next.config.js
  packages/client/package.json
  packages/client/styles/globals.css
  packages/client/tailwind.config.js
  prettier.config.js
Labels: dev-experience

#50 Update & bump dependencies
  package-lock.json
  package.json
  packages/client/lib/components/ReportForm/FormViews/SummaryView.jsx
  packages/client/package.json
Labels: bug, dev-experience

#52 GitHub Actions and GitHub Pages for CI
  .github/workflows/nextjs.yml
Labels: enhancement, dev-experience

#54 Fix GH Actions Deploy Pages
  .github/workflows/nextjs.yml
Labels: bug

#57 Fix for mobile viewport innerheight
  packages/client/lib/components/LocationSearch.jsx
  packages/client/lib/components/Map.jsx
  packages/client/lib/components/ReportForm/FormViews/UpdateView.jsx
  packages/client/lib/components/ReportForm/NavigationButtons/SubmitReportForm.jsx
  packages/client/lib/components/ReportForm/ReportForm.jsx
  packages/client/lib/hooks/useResizeWindow.jsx
  packages/client/next.config.js
  packages/client/pages/_app.tsx
  packages/client/store/store.js
  packages/client/styles/globals.css
  packages/client/tailwind.config.js
Labels: bug, enhancement

#60 Add Netlify-cli and deploy
  .github/workflows/nextjs.yml
  .gitignore
  netlify.toml
  package-lock.json
  packages/client/lib/components/ReportForm/NavigationButtons/FormButtons.jsx
  packages/client/lib/components/ReportForm/ReportForm.jsx
  packages/client/next.config.js
  packages/client/package.json
Labels: bug, dev-experience
